Dev rules
WildCodeSchool/happiness_and_glitters pull request #4
Opened 2022-11-25 11:17 UTC by td6904

2022-11-25 14:03 UTC, Benja-san requested changes

2022-11-25 14:03 UTC, Benja-san commented on assets/styles/_userForm.scss
> +h2,
use class instead of tags, especially for components

2022-11-25 14:03 UTC, Benja-san commented on templates/base.html.twig
> +			{% block title %}Happiness and Glitters
Put the global name of the brand above the title block

2022-11-25 14:03 UTC, Benja-san commented on templates/component/_header.html.twig
> +	{#{% if sessionUser %}
can you remove it ?

2022-11-25 14:03 UTC, Benja-san commented on templates/base.html.twig
> +			{{ encore_entry_link_tags('app') }}
Put the global script outside the stylesheet block in order to avoid repeating parent() function

2022-11-25 14:03 UTC, Benja-san commented on templates/rules/index.html.twig
> +		<script type="application/javascript" src="/assets/js/formModale.js"></script>
If you can addentries and use the entries properties it would be better

2022-11-28 10:48 UTC, serhanif59 approved these changes

2022-11-28 11:11 UTC, Benja-san approved these changes

2022-11-28 14:53 UTC, merged